apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: zx10bs37c-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-04c785e147.ymto.p3.openshiftapps.com/rhtap/rhtap-qe:df64985803f1b2026ae7d660f973c84f721e53a2@sha256:e0c38f9da1010cc32a79eed73f91fbb9fb149745c11885440ef26a782feaaf85
          name: container-image
